[package]
name    = "anvil-crud"
version = "0.1.0"
forge   = "0.1.0"
entry   = "src/main.forge"

[dependencies]
anvil    = { path = "../../packages/anvil" }
crucible = { path = "../../packages/crucible" }
