use std::fs;
use std::path::Path;

const CRUCIBLE_TOML: &str = r#"[database]
driver   = "postgres"
host     = "localhost"
port     = 5432
name     = "myapp_dev"
user     = "postgres"
password = ""

[migrations]
directory = "migrations"
table     = "_crucible_migrations"
"#;

const MIGRATION_001: &str = r#"-- +migrate Up
CREATE TABLE users (
    id         SERIAL       PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at TIMESTAMP    NOT NULL DEFAULT now()
);

-- +migrate Down
DROP TABLE users;
"#;

const USER_FORGE: &str = r#"// User model — generated by crucible init
// Edit this file to define your User model.

struct User {
    id: number
    name: string
    email: string
    password: string
}
"#;

/// ベースディレクトリに crucible プロジェクトを初期化する
fn run_init_in(base: &Path, use_psql: bool) -> Result<(), String> {
    // crucible.toml を生成する
    let toml_path = base.join("crucible.toml");
    if toml_path.exists() {
        println!("crucible.toml はすでに存在します。スキップします。");
    } else {
        fs::write(&toml_path, CRUCIBLE_TOML)
            .map_err(|e| format!("crucible.toml の生成に失敗しました: {}", e))?;
        println!("生成: crucible.toml");
    }

    // migrations/ ディレクトリを作成する
    let migrations_dir = base.join("migrations");
    if !migrations_dir.exists() {
        fs::create_dir(&migrations_dir)
            .map_err(|e| format!("migrations/ ディレクトリの作成に失敗しました: {}", e))?;
        println!("作成: migrations/");
    }

    // migrations/001_create_users.sql を生成する
    let migration_path = migrations_dir.join("001_create_users.sql");
    if migration_path.exists() {
        println!("migrations/001_create_users.sql はすでに存在します。スキップします。");
    } else {
        fs::write(&migration_path, MIGRATION_001).map_err(|e| {
            format!(
                "migrations/001_create_users.sql の生成に失敗しました: {}",
                e
            )
        })?;
        println!("生成: migrations/001_create_users.sql");
    }

    // src/models/ ディレクトリを作成する
    let models_dir = base.join("src").join("models");
    if !models_dir.exists() {
        fs::create_dir_all(&models_dir)
            .map_err(|e| format!("src/models/ ディレクトリの作成に失敗しました: {}", e))?;
        println!("作成: src/models/");
    }

    // src/models/user.forge を生成する
    let user_forge_path = models_dir.join("user.forge");
    if user_forge_path.exists() {
        println!("src/models/user.forge はすでに存在します。スキップします。");
    } else {
        fs::write(&user_forge_path, USER_FORGE)
            .map_err(|e| format!("src/models/user.forge の生成に失敗しました: {}", e))?;
        println!("生成: src/models/user.forge");
    }

    if use_psql {
        println!("\nPostgreSQL 用プロジェクトを初期化しました。");
        println!("次のステップ:");
        println!("  1. crucible.toml のデータベース設定を編集してください");
        println!("  2. crucible migrate を実行してマイグレーションを適用してください");
    } else {
        println!("\nプロジェクトを初期化しました。");
    }

    Ok(())
}

/// カレントディレクトリに crucible プロジェクトを初期化する（CLI エントリポイント）
pub fn run_init(use_psql: bool) -> Result<(), String> {
    let base = std::env::current_dir()
        .map_err(|e| format!("カレントディレクトリの取得に失敗しました: {}", e))?;
    run_init_in(&base, use_psql)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn test_run_init_creates_files() {
        let tmp = TempDir::new().unwrap();
        let result = run_init_in(tmp.path(), true);

        assert!(result.is_ok(), "run_init failed: {:?}", result);

        let base = tmp.path();
        assert!(base.join("crucible.toml").exists());
        assert!(base.join("migrations").is_dir());
        assert!(base.join("migrations/001_create_users.sql").exists());
        assert!(base.join("src/models").is_dir());
        assert!(base.join("src/models/user.forge").exists());
    }

    #[test]
    fn test_crucible_toml_content() {
        let tmp = TempDir::new().unwrap();
        run_init_in(tmp.path(), false).unwrap();

        let content = fs::read_to_string(tmp.path().join("crucible.toml")).unwrap();
        assert!(content.contains("[database]"));
        assert!(content.contains("host     = \"localhost\""));
        assert!(content.contains("port     = 5432"));
        assert!(content.contains("name     = \"myapp_dev\""));
        assert!(content.contains("[migrations]"));
        assert!(content.contains("directory = \"migrations\""));
        assert!(content.contains("table     = \"_crucible_migrations\""));
    }

    #[test]
    fn test_migration_001_content() {
        let tmp = TempDir::new().unwrap();
        run_init_in(tmp.path(), false).unwrap();

        let content =
            fs::read_to_string(tmp.path().join("migrations/001_create_users.sql")).unwrap();
        assert!(content.contains("-- +migrate Up"));
        assert!(content.contains("CREATE TABLE users"));
        assert!(content.contains("-- +migrate Down"));
        assert!(content.contains("DROP TABLE users"));
    }

    #[test]
    fn test_user_forge_content() {
        let tmp = TempDir::new().unwrap();
        run_init_in(tmp.path(), false).unwrap();

        let content = fs::read_to_string(tmp.path().join("src/models/user.forge")).unwrap();
        assert!(content.contains("struct User"));
        assert!(content.contains("id: number"));
        assert!(content.contains("name: string"));
        assert!(content.contains("email: string"));
    }
}
