use std::fs;
use std::path::Path;

/// 指定ディレクトリ内の .sql ファイル数から次のバージョン番号を計算する
fn next_migration_version_in(dir: &Path) -> Result<String, String> {
    if !dir.exists() {
        fs::create_dir_all(dir)
            .map_err(|e| format!("migrations ディレクトリの作成に失敗しました: {}", e))?;
        return Ok("001".to_string());
    }

    let count = fs::read_dir(dir)
        .map_err(|e| format!("ディレクトリの読み込みに失敗しました: {}", e))?
        .filter_map(|entry| entry.ok())
        .filter(|entry| {
            entry
                .path()
                .extension()
                .and_then(|ext| ext.to_str())
                .map(|ext| ext == "sql")
                .unwrap_or(false)
        })
        .count();

    Ok(format!("{:03}", count + 1))
}

/// カレントディレクトリを基準に次のバージョン番号を計算する（CLI 用）
fn next_migration_version(dir: &str) -> Result<String, String> {
    next_migration_version_in(Path::new(dir))
}

/// PascalCase を snake_case に変換する
fn pascal_to_snake(name: &str) -> String {
    let mut result = String::new();
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            result.push('_');
        }
        result.push(ch.to_lowercase().next().unwrap());
    }
    result
}

/// make:migration <name> — migrations/{NNN}_{name}.sql を作成する
pub fn run_make_migration(name: &str) -> Result<(), String> {
    let dir = "migrations";
    let version = next_migration_version(dir)?;
    let filename = format!("{}/{}_{}.sql", dir, version, name);

    if Path::new(&filename).exists() {
        return Err(format!("{} はすでに存在します", filename));
    }

    let content = format!(
        "-- +migrate Up\n-- TODO: {}\n\n-- +migrate Down\n-- TODO: undo {}\n",
        name, name
    );

    fs::write(&filename, content)
        .map_err(|e| format!("マイグレーションファイルの生成に失敗しました: {}", e))?;

    println!("生成: {}", filename);
    Ok(())
}

/// make:model <Name> — src/models/{name_snake}.forge に struct を作成する
pub fn run_make_model(name: &str) -> Result<(), String> {
    let snake = pascal_to_snake(name);
    let dir = "src/models";
    let filename = format!("{}/{}.forge", dir, snake);

    if !Path::new(dir).exists() {
        fs::create_dir_all(dir)
            .map_err(|e| format!("src/models/ ディレクトリの作成に失敗しました: {}", e))?;
    }

    if Path::new(&filename).exists() {
        return Err(format!("{} はすでに存在します", filename));
    }

    let content = format!(
        "// {} model — generated by crucible make:model\n// Edit this file to define your {} model.\n\nstruct {} {{\n    id: number\n}}\n",
        name, name, name
    );

    fs::write(&filename, content)
        .map_err(|e| format!("モデルファイルの生成に失敗しました: {}", e))?;

    println!("生成: {}", filename);
    Ok(())
}

/// make:repo <Name> — src/repositories/{name_snake}_repository.forge を作成する
pub fn run_make_repo(name: &str) -> Result<(), String> {
    let snake = pascal_to_snake(name);
    let dir = "src/repositories";
    let filename = format!("{}/{}_repository.forge", dir, snake);

    if !Path::new(dir).exists() {
        fs::create_dir_all(dir)
            .map_err(|e| format!("src/repositories/ ディレクトリの作成に失敗しました: {}", e))?;
    }

    if Path::new(&filename).exists() {
        return Err(format!("{} はすでに存在します", filename));
    }

    let table = format!("{}s", snake);
    let content = format!(
        "// {}Repository — generated by crucible make:repo\n// Edit this file to implement your repository.\n\nstruct {}Repository {{\n    conn: Conn\n}}\n\nfn new_{}_repository(conn: Conn) -> {}Repository {{\n    {}Repository {{ conn: conn }}\n}}\n\nfn find_all(repo: {}Repository) -> list<map>! {{\n    all_rows(repo.conn, \"{}\")\n}}\n\nfn find_by_id(repo: {}Repository, id: number) -> map! {{\n    find_by_id(repo.conn, \"{}\", id)\n}}\n",
        name, name, snake, name, name, name, table, name, table
    );

    fs::write(&filename, content)
        .map_err(|e| format!("リポジトリファイルの生成に失敗しました: {}", e))?;

    println!("生成: {}", filename);
    Ok(())
}

// ── テスト用ベースディレクトリを受け取る内部関数 ───────────────────────────

fn run_make_migration_in(base: &Path, name: &str) -> Result<(), String> {
    let dir = base.join("migrations");
    let version = next_migration_version_in(&dir)?;
    let filename = dir.join(format!("{}_{}.sql", version, name));

    if filename.exists() {
        return Err(format!("{} はすでに存在します", filename.display()));
    }

    let content = format!(
        "-- +migrate Up\n-- TODO: {}\n\n-- +migrate Down\n-- TODO: undo {}\n",
        name, name
    );

    fs::write(&filename, content)
        .map_err(|e| format!("マイグレーションファイルの生成に失敗しました: {}", e))?;

    println!("生成: {}", filename.display());
    Ok(())
}

fn run_make_model_in(base: &Path, name: &str) -> Result<(), String> {
    let snake = pascal_to_snake(name);
    let dir = base.join("src").join("models");
    let filename = dir.join(format!("{}.forge", snake));

    if !dir.exists() {
        fs::create_dir_all(&dir)
            .map_err(|e| format!("src/models/ ディレクトリの作成に失敗しました: {}", e))?;
    }

    if filename.exists() {
        return Err(format!("{} はすでに存在します", filename.display()));
    }

    let content = format!(
        "// {} model — generated by crucible make:model\n// Edit this file to define your {} model.\n\nstruct {} {{\n    id: number\n}}\n",
        name, name, name
    );

    fs::write(&filename, content)
        .map_err(|e| format!("モデルファイルの生成に失敗しました: {}", e))?;

    println!("生成: {}", filename.display());
    Ok(())
}

fn run_make_repo_in(base: &Path, name: &str) -> Result<(), String> {
    let snake = pascal_to_snake(name);
    let dir = base.join("src").join("repositories");
    let filename = dir.join(format!("{}_repository.forge", snake));

    if !dir.exists() {
        fs::create_dir_all(&dir)
            .map_err(|e| format!("src/repositories/ ディレクトリの作成に失敗しました: {}", e))?;
    }

    if filename.exists() {
        return Err(format!("{} はすでに存在します", filename.display()));
    }

    let table = format!("{}s", snake);
    let content = format!(
        "// {}Repository — generated by crucible make:repo\n// Edit this file to implement your repository.\n\nstruct {}Repository {{\n    conn: Conn\n}}\n\nfn new_{}_repository(conn: Conn) -> {}Repository {{\n    {}Repository {{ conn: conn }}\n}}\n\nfn find_all(repo: {}Repository) -> list<map>! {{\n    all_rows(repo.conn, \"{}\")\n}}\n\nfn find_by_id(repo: {}Repository, id: number) -> map! {{\n    find_by_id(repo.conn, \"{}\", id)\n}}\n",
        name, name, snake, name, name, name, table, name, table
    );

    fs::write(&filename, content)
        .map_err(|e| format!("リポジトリファイルの生成に失敗しました: {}", e))?;

    println!("生成: {}", filename.display());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn test_pascal_to_snake() {
        assert_eq!(pascal_to_snake("User"), "user");
        assert_eq!(pascal_to_snake("UserProfile"), "user_profile");
        assert_eq!(pascal_to_snake("BlogPost"), "blog_post");
    }

    #[test]
    fn test_next_migration_version_empty_dir() {
        let tmp = TempDir::new().unwrap();
        let dir = tmp.path().join("migrations");
        fs::create_dir(&dir).unwrap();
        let version = next_migration_version_in(&dir).unwrap();
        assert_eq!(version, "001");
    }

    #[test]
    fn test_run_make_migration() {
        let tmp = TempDir::new().unwrap();
        fs::create_dir(tmp.path().join("migrations")).unwrap();

        run_make_migration_in(tmp.path(), "add_posts_table").unwrap();

        let path = tmp.path().join("migrations/001_add_posts_table.sql");
        assert!(path.exists());
        let content = fs::read_to_string(&path).unwrap();
        assert!(content.contains("-- +migrate Up"));
        assert!(content.contains("-- +migrate Down"));
    }

    #[test]
    fn test_run_make_model() {
        let tmp = TempDir::new().unwrap();

        run_make_model_in(tmp.path(), "BlogPost").unwrap();

        let path = tmp.path().join("src/models/blog_post.forge");
        assert!(path.exists());
        let content = fs::read_to_string(&path).unwrap();
        assert!(content.contains("struct BlogPost"));
    }

    #[test]
    fn test_run_make_repo() {
        let tmp = TempDir::new().unwrap();

        run_make_repo_in(tmp.path(), "User").unwrap();

        let path = tmp.path().join("src/repositories/user_repository.forge");
        assert!(path.exists());
        let content = fs::read_to_string(&path).unwrap();
        assert!(content.contains("struct UserRepository"));
    }
}
