use std::collections::BTreeMap;
use std::fs;
use tokio_postgres::NoTls;

use crate::config::Config;

/// テーブル内のカラム情報
#[derive(Debug)]
struct ColumnInfo {
    name: String,
    data_type: String,
    is_nullable: bool,
}

/// information_schema から テーブル→カラム情報のマップを取得する
async fn fetch_schema(
    client: &tokio_postgres::Client,
) -> Result<BTreeMap<String, Vec<ColumnInfo>>, String> {
    let sql = "SELECT table_name, column_name, data_type, is_nullable \
               FROM information_schema.columns \
               WHERE table_schema = 'public' \
               ORDER BY table_name, ordinal_position";

    let rows = client
        .query(sql, &[])
        .await
        .map_err(|e| format!("スキーマの取得に失敗しました: {}", e))?;

    let mut schema: BTreeMap<String, Vec<ColumnInfo>> = BTreeMap::new();

    for row in &rows {
        let table_name: String = row.get(0);
        let column_name: String = row.get(1);
        let data_type: String = row.get(2);
        let is_nullable_str: String = row.get(3);
        let is_nullable = is_nullable_str == "YES";

        schema.entry(table_name).or_default().push(ColumnInfo {
            name: column_name,
            data_type,
            is_nullable,
        });
    }

    Ok(schema)
}

/// PostgreSQL のデータ型を ForgeScript の型に変換する
fn pg_type_to_forge(pg_type: &str) -> &str {
    match pg_type {
        "integer" | "bigint" | "smallint" | "serial" | "bigserial" | "numeric" | "real"
        | "double precision" => "number",
        "boolean" => "bool",
        "timestamp without time zone"
        | "timestamp with time zone"
        | "date"
        | "time without time zone"
        | "time with time zone" => "string",
        "json" | "jsonb" => "map",
        _ => "string",
    }
}

/// スキーマ情報から schema.forge のソースコードを生成する
fn generate_schema_forge_source(schema: &BTreeMap<String, Vec<ColumnInfo>>) -> String {
    let mut lines = Vec::new();
    lines.push("// schema.forge — generated by crucible schema:sync".to_string());
    lines.push("// DO NOT EDIT: このファイルは自動生成されます".to_string());
    lines.push(String::new());

    for (table_name, columns) in schema {
        // テーブル名を PascalCase に変換する
        let struct_name = snake_to_pascal(table_name);
        lines.push(format!("// テーブル: {}", table_name));
        lines.push(format!("struct {} {{", struct_name));

        for col in columns {
            let forge_type = pg_type_to_forge(&col.data_type);
            let type_annotation = if col.is_nullable {
                format!("{}?", forge_type)
            } else {
                forge_type.to_string()
            };
            lines.push(format!("    {}: {}", col.name, type_annotation));
        }

        lines.push("}".to_string());
        lines.push(String::new());
    }

    lines.join("\n")
}

/// snake_case を PascalCase に変換する
fn snake_to_pascal(name: &str) -> String {
    name.split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

/// schema:sync — information_schema を読んで src/schema.forge を生成する
pub async fn run_schema_sync(config: &Config) -> Result<(), String> {
    let (client, connection) = tokio_postgres::connect(&config.connection_string(), NoTls)
        .await
        .map_err(|e| format!("PostgreSQL への接続に失敗しました: {}", e))?;

    tokio::spawn(async move {
        if let Err(e) = connection.await {
            eprintln!("接続エラー: {}", e);
        }
    });

    let schema = fetch_schema(&client).await?;

    if schema.is_empty() {
        println!("public スキーマにテーブルが見つかりません。");
        return Ok(());
    }

    let source = generate_schema_forge_source(&schema);

    // src/ ディレクトリを作成する
    if !std::path::Path::new("src").exists() {
        fs::create_dir("src")
            .map_err(|e| format!("src/ ディレクトリの作成に失敗しました: {}", e))?;
    }

    fs::write("src/schema.forge", &source)
        .map_err(|e| format!("src/schema.forge の生成に失敗しました: {}", e))?;

    println!("生成: src/schema.forge ({} テーブル)", schema.len());
    Ok(())
}

/// schema:diff — モデル定義と DB スキーマの差分を表示する
pub async fn run_schema_diff(config: &Config) -> Result<(), String> {
    let (client, connection) = tokio_postgres::connect(&config.connection_string(), NoTls)
        .await
        .map_err(|e| format!("PostgreSQL への接続に失敗しました: {}", e))?;

    tokio::spawn(async move {
        if let Err(e) = connection.await {
            eprintln!("接続エラー: {}", e);
        }
    });

    let schema = fetch_schema(&client).await?;

    // src/schema.forge が存在する場合は読み込む
    let current_source = fs::read_to_string("src/schema.forge").unwrap_or_default();
    let new_source = generate_schema_forge_source(&schema);

    if current_source == new_source {
        println!("スキーマに差分はありません。");
    } else {
        println!("スキーマに差分が検出されました:");
        println!("  crucible schema:sync を実行して src/schema.forge を更新してください。");

        // テーブル一覧を表示する
        println!("\nDB のテーブル:");
        for (table_name, columns) in &schema {
            println!("  {} ({} カラム)", table_name, columns.len());
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_snake_to_pascal() {
        assert_eq!(snake_to_pascal("users"), "Users");
        assert_eq!(snake_to_pascal("blog_posts"), "BlogPosts");
        assert_eq!(
            snake_to_pascal("user_profile_settings"),
            "UserProfileSettings"
        );
    }

    #[test]
    fn test_pg_type_to_forge() {
        assert_eq!(pg_type_to_forge("integer"), "number");
        assert_eq!(pg_type_to_forge("boolean"), "bool");
        assert_eq!(pg_type_to_forge("character varying"), "string");
        assert_eq!(pg_type_to_forge("jsonb"), "map");
        assert_eq!(pg_type_to_forge("timestamp without time zone"), "string");
    }

    #[test]
    fn test_generate_schema_forge_source() {
        let mut schema = BTreeMap::new();
        schema.insert(
            "users".to_string(),
            vec![
                ColumnInfo {
                    name: "id".to_string(),
                    data_type: "integer".to_string(),
                    is_nullable: false,
                },
                ColumnInfo {
                    name: "name".to_string(),
                    data_type: "character varying".to_string(),
                    is_nullable: false,
                },
                ColumnInfo {
                    name: "email".to_string(),
                    data_type: "character varying".to_string(),
                    is_nullable: true,
                },
            ],
        );

        let source = generate_schema_forge_source(&schema);
        assert!(source.contains("struct Users {"));
        assert!(source.contains("    id: number"));
        assert!(source.contains("    name: string"));
        assert!(source.contains("    email: string?"));
    }
}
